[package]
name = "sum_tree"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/sum_tree.rs"
doctest = false

[dependencies]
arrayvec = "0.7.1"
log = { version = "0.4.16", features = ["kv_unstable_serde"] }

[dev-dependencies]
ctor = "0.1"
env_logger = "0.9"
rand = "0.8.3"
