[package]
name = "go_to_line"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/go_to_line.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
gpui = { path = "../gpui" }
menu = { path = "../menu" }
settings = { path = "../settings" }
text = { path = "../text" }
workspace = { path = "../workspace" }
postage = { version = "0.4", features = ["futures-traits"] }
