[package]
name = "journal"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/journal.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
gpui = { path = "../gpui" }
util = { path = "../util" }
workspace = { path = "../workspace" }
chrono = "0.4"
dirs = "4.0"
log = { version = "0.4.16", features = ["kv_unstable_serde"] }
settings = { path = "../settings" }
shellexpand = "2.1.0"