[package]
name = "theme"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/theme.rs"
doctest = false

[dependencies]
gpui = { path = "../gpui" }
anyhow = "1.0.38"
indexmap = "1.6.2"
parking_lot = "0.11.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_path_to_error = "0.1.4"
toml = "0.5"
