[package]
name = "drag_and_drop"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/drag_and_drop.rs"
doctest = false

[dependencies]
collections = { path = "../collections" }
gpui = { path = "../gpui" }

[dev-dependencies]
gpui = { path = "../gpui", features = ["test-support"] }