[package]
name = "plugin_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "0.38"
wasmtime-wasi = "0.38"
wasi-common = "0.38"
anyhow = { version = "1.0", features = ["std"] }
serde = "1.0"
serde_json = "1.0"
bincode = "1.3"
pollster = "0.2.5"
smol = "1.2.5"

[build-dependencies]
wasmtime = { version = "0.38", features = ["all-arch"] }
