[package]
name = "rope"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/rope.rs"

[dependencies]
bromberg_sl2 = "0.6"
smallvec = { version = "1.6", features = ["union"] }
sum_tree = { path = "../sum_tree" }
arrayvec = "0.7.1"
log = { version = "0.4.16", features = ["kv_unstable_serde"] }


[dev-dependencies]
rand = "0.8.3"
util = { path = "../util", features = ["test-support"] }
gpui = { path = "../gpui", features = ["test-support"]  }
